### ISSUE TITLE
Force close 

### ISSUE THREAD

**Issue by MarceloMachadoxD** [phoenixbyrd/Termux_XFCE#63]
Running ide 

## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxActivity`  
**Report Timestamp**: `2024-10-04 11:51:32.127 UTC`  
##

## Crash Details

**Crash Thread**: `Thread[main,5,main]`  
**Crash Timestamp**: `2024-10-04 11:51:30.508 UTC`  

**Crash Message**:
```
Unable to start activity ComponentInfo{com.termux/com.termux.app.TermuxActivity}: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.termux/.app.TermuxService }: app is in background uid UidRecord{b4fe07 u0a281 CEM  idle procs:1 proclist:10088, seq(0,0,0)}
```

### Stacktrace

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.termux/com.termux.app.TermuxActivity}: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.termux/.app.TermuxService }: app is in background uid UidRecord{b4fe07 u0a281 CEM  idle procs:1 proclist:10088, seq(0,0,0)}
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.termux/.app.TermuxService }: app is in background uid UidRecord{b4fe07 u0a281 CEM  idle procs:1 proclist:10088, seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1688)
	at android.app.ContextImpl.startService(ContextImpl.java:1633)
	at android.content.ContextWrapper.startService(ContextWrapper.java:683)
	at com.termux.app.TermuxActivity.onCreate(TermuxActivity.java:242)
	at android.app.Activity.performCreate(Activity.java:7963)
	at android.app.Activity.performCreate(Activity.java:7952)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
	... 11 more

```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.1`  
**VERSION_CODE**: `1000`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `4.9.186-22986754`  
**SDK_INT**: `29`  
**RELEASE**: `10`  
**ID**: `QP1A.190711.020`  
**DISPLAY**: `QP1A.190711.020.G9600ZHU9FVF2`  
**INCREMENTAL**: `G9600ZHU9FVF2`  
**SECURITY_PATCH**: `2022-05-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `samsung`  
**BRAND**: `samsung`  
**MODEL**: `SM-G9600`  
**PRODUCT**: `starqltezh`  
**BOARD**: `sdm845`  
**HARDWARE**: `qcom`  
**DEVICE**: `starqltechn`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

**Comment by phoenixbyrd** [comment]
idk what any of that even means. Can you dumb down the issue in easier to digest and understand chunks? Explain what you're trying to do and what's happening. I can't guess it based on gibberish.

**Comment by MarceloMachadoxD** [comment]
> idk what any of that even means. Can you dumb down the issue in easier to digest and understand chunks? Explain what you're trying to do and what's happening. I can't guess it based on gibberish. 

The error occour oppening the intellij inside termux and wait graddle download dependencies
It simple close termux x11 and appear a window asking to copy this message that you call as gibberish to report the issue

**Comment by phoenixbyrd** [comment]
idk anything about intellij or why it might cause issues in termux. I've never received an error like that before when closing termux x11.
